// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEntry(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddEntry'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateVault(arg1, arg2) {
  return window['go']['main']['App']['CreateVault'](arg1, arg2);
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function GetEntries() {
  return window['go']['main']['App']['GetEntries']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LockVault() {
  return window['go']['main']['App']['LockVault']();
}

export function SelectNewVaultPath() {
  return window['go']['main']['App']['SelectNewVaultPath']();
}

export function SelectVaultPath() {
  return window['go']['main']['App']['SelectVaultPath']();
}

export function UnlockVault(arg1, arg2) {
  return window['go']['main']['App']['UnlockVault'](arg1, arg2);
}

export function UpdateEntry(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateEntry'](arg1, arg2, arg3, arg4, arg5, arg6);
}
